# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
    build:
      working_directory: ~/serviceless
      docker:
          - image: circleci/node:6.10.3

      steps:
          - checkout
          # Download and cache dependencies
          - restore_cache:
              keys:
                  - v1-dependencies-{{ checksum "package-lock.json" }}
                  # fallback to using the latest cache if no exact match is found
                  - v1-dependencies-

          - run:
              name: install dependencies
              command: npm install

          - save_cache:
              paths:
                  - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}

          - run:
              name: Test
              command: npm run test:coverage

          - run:
              name: Upload coverage report
              command: npm run codecov

          - store_artifacts:
              path: coverage
              prefix: coverage
